<a href="https://colab.research.google.com/github/jucav-145/saudades-de-casa/blob/main/Data%20Mining%20Mushroom%20Dataset%20-%20Machine%20Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [329]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [330]:
df = pd.read_csv('Dataset.csv')

In [331]:
df

ASS cap_shape cap_surface cap_color bruises odor gill_attachment  \
0      p         x           s         n       t    p               f   
1      e         x           s         y       t    a               f   
2      e         b           s         w       t    l               f   
3      p         x           y         w       t    p               f   
4      e         x           s         g       f    n               f   
...   ..       ...         ...       ...     ...  ...             ...   
8119   e         k           s         n       f    n               a   
8120   e         x           s         n       f    n               a   
8121   e         f           s         n       f    n               a   
8122   p         k           y         n       f    y               f   
8123   e         x           s         n       f    n               a   

     gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring_number ring_type spore_print_color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [332]:
df.describe

<bound method NDFrame.describe of      ASS cap_shape cap_surface cap_color bruises odor gill_attachment  \
0      p         x           s         n       t    p               f   
1      e         x           s         y       t    a               f   
2      e         b           s         w       t    l               f   
3      p         x           y         w       t    p               f   
4      e         x           s         g       f    n               f   
...   ..       ...         ...       ...     ...  ...             ...   
8119   e         k           s         n       f    n               a   
8120   e         x           s         n       f    n               a   
8121   e         f           s         n       f    n               a   
8122   p         k           y         n       f    y               f   
8123   e         x           s         n       f    n               a   

     gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0               c

In [333]:
df.isnull().sum()

ASS                            0
cap_shape                      0
cap_surface                    0
cap_color                      0
bruises                        0
odor                           0
gill_attachment                0
gill_spacing                   0
gill_size                      0
gill_color                     0
stalk_shape                    0
stalk_root                  2480
stalk_surface_above_ring       0
stalk_surface_below_ring       0
stalk_color_above_ring         0
stalk_color_below_ring         0
veil_type                      0
veil_color                     0
ring_number                    0
ring_type                      0
spore_print_color              0
population                     0
habitat                        0
dtype: int64

In [334]:
df.drop('stalk_root', axis=1, inplace=True)

In [335]:
df.isnull().sum()

ASS                         0
cap_shape                   0
cap_surface                 0
cap_color                   0
bruises                     0
odor                        0
gill_attachment             0
gill_spacing                0
gill_size                   0
gill_color                  0
stalk_shape                 0
stalk_surface_above_ring    0
stalk_surface_below_ring    0
stalk_color_above_ring      0
stalk_color_below_ring      0
veil_type                   0
veil_color                  0
ring_number                 0
ring_type                   0
spore_print_color           0
population                  0
habitat                     0
dtype: int64

In [336]:
print(df.dtypes)

ASS                         object
cap_shape                   object
cap_surface                 object
cap_color                   object
bruises                     object
odor                        object
gill_attachment             object
gill_spacing                object
gill_size                   object
gill_color                  object
stalk_shape                 object
stalk_surface_above_ring    object
stalk_surface_below_ring    object
stalk_color_above_ring      object
stalk_color_below_ring      object
veil_type                   object
veil_color                  object
ring_number                 object
ring_type                   object
spore_print_color           object
population                  object
habitat                     object
dtype: object


In [337]:
#Label Encoder
from sklearn.preprocessing import LabelEncoder

In [338]:
#ASS                         object
#cap_shape                   object
#cap_surface                 object
#cap_color                   object
#bruises                     object
#odor                        object
#gill_attachment             object
#gill_spacing                object
#gill_size                   object
#gill_color                  object
#stalk_shape                 object
#stalk_surface_above_ring    object
#stalk_surface_below_ring    object
#stalk_color_above_ring      object
#stalk_color_below_ring      object
#veil_type                   object
#veil_color                  object
#ring_number                 object
#ring_type                   object
#spore_print_color           object
#population                  object
#habitat                     object

label_encoder_ASS = LabelEncoder()
label_encoder_cap_shape = LabelEncoder()
label_encoder_cap_surface = LabelEncoder()
label_encoder_cap_color = LabelEncoder()  
label_encoder_bruises = LabelEncoder()
label_encoder_odor = LabelEncoder()
label_encoder_gill_attachment = LabelEncoder()
label_encoder_gill_spacing = LabelEncoder()
label_encoder_gill_size = LabelEncoder()
label_encoder_gill_color = LabelEncoder()
label_encoder_stalk_shape = LabelEncoder()
label_encoder_stalk_surface_above_ring = LabelEncoder()
label_encoder_stalk_surface_below_ring = LabelEncoder()
label_encoder_stalk_color_above_ring = LabelEncoder()
label_encoder_stalk_color_below_ring = LabelEncoder()
label_encoder_veil_type = LabelEncoder()
label_encoder_veil_color = LabelEncoder()
label_encoder_ring_number = LabelEncoder()
label_encoder_ring_type = LabelEncoder()
label_encoder_spore_print_color = LabelEncoder()
label_encoder_population = LabelEncoder()
label_encoder_habitat = LabelEncoder()

In [339]:
df.iloc[:,0] = label_encoder_ASS.fit_transform(df.iloc[:,0])
df.iloc[:,1] = label_encoder_cap_shape.fit_transform(df.iloc[:,1])
df.iloc[:,2] = label_encoder_cap_surface.fit_transform(df.iloc[:,2])
df.iloc[:,3] = label_encoder_cap_color.fit_transform(df.iloc[:,3]) 
df.iloc[:,4] = label_encoder_bruises.fit_transform(df.iloc[:,4])
df.iloc[:,5] = label_encoder_odor.fit_transform(df.iloc[:,5])
df.iloc[:,6] = label_encoder_gill_attachment.fit_transform(df.iloc[:,6])
df.iloc[:,7] = label_encoder_gill_spacing.fit_transform(df.iloc[:,7])
df.iloc[:,8] = label_encoder_gill_size.fit_transform(df.iloc[:,8])
df.iloc[:,9] = label_encoder_gill_color.fit_transform(df.iloc[:,9])
df.iloc[:,10] = label_encoder_stalk_shape.fit_transform(df.iloc[:,10])
df.iloc[:,11] = label_encoder_stalk_surface_above_ring.fit_transform(df.iloc[:,11])
df.iloc[:,12] = label_encoder_stalk_surface_below_ring.fit_transform(df.iloc[:,12])
df.iloc[:,13] = label_encoder_stalk_color_above_ring.fit_transform(df.iloc[:,13])
df.iloc[:,14] = label_encoder_stalk_color_below_ring.fit_transform(df.iloc[:,14])
df.iloc[:,15] = label_encoder_veil_type.fit_transform(df.iloc[:,15])
df.iloc[:,16] = label_encoder_veil_color.fit_transform(df.iloc[:,16])
df.iloc[:,17] = label_encoder_ring_number.fit_transform(df.iloc[:,17])
df.iloc[:,18] = label_encoder_ring_type.fit_transform(df.iloc[:,18])
df.iloc[:,19] = label_encoder_spore_print_color.fit_transform(df.iloc[:,19])
df.iloc[:,20] = label_encoder_population.fit_transform(df.iloc[:,20])
df.iloc[:,21] = label_encoder_habitat.fit_transform(df.iloc[:,21])


In [340]:
df

ASS  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0       1          5            2          4        1     6                1   
1       0          5            2          9        1     0                1   
2       0          0            2          8        1     3                1   
3       1          5            3          8        1     6                1   
4       0          5            2          3        0     5                1   
...   ...        ...          ...        ...      ...   ...              ...   
8119    0          3            2          4        0     5                0   
8120    0          5            2          4        0     5                0   
8121    0          2            2          4        0     5                0   
8122    1          3            3          4        0     8                1   
8123    0          5            2          4        0     5                0   

      gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring  \
0                0          1           4  ...                         2   
1                0          0           4  ...                         2   
2                0          0           5  ...                         2   
3                0          1           5  ...                         2   
4                1          0           4  ...                         2   
...            ...        ...         ...  ...                       ...   
8119             0          0          11  ...                         2   
8120             0          0          11  ...                         2   
8121             0          0           5  ...                         2   
8122             0          1           0  ...                         1   
8123             0          0          11  ...                         2   

      stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                          7                       7          0           2   
1                          7                       7          0           2   
2                          7                       7          0           2   
3                          7                       7          0           2   
4                          7                       7          0           2   
...                      ...                     ...        ...         ...   
8119                       5                       5          0           1   
8120                       5                       5          0           0   
8121                       5                       5          0           1   
8122                       7                       7          0           2   
8123                       5                       5          0           1   

      ring_number  ring_type  spore_print_color  population  habitat  
0               1          4                  2           3        5  
1               1          4                  3           2        1  
2               1          4                  3           2        3  
3               1          4                  2           3        5  
4               1          0                  3           0        1  
...           ...        ...                ...         ...      ...  
8119            1          4                  0           1        2  
8120            1          4                  0           4        2  
8121            1          4                  0           1        2  
8122            1          0                  7           4        2  
8123            1          4                  4           1        2  

[8124 rows x 22 columns]

In [341]:
#Divisão entre previsores e classe
df_x = df.iloc[:, 1:22].values

In [342]:
df_x

array([[5, 2, 4, ..., 2, 3, 5],
       [5, 2, 9, ..., 3, 2, 1],
       [0, 2, 8, ..., 3, 2, 3],
       ...,
       [2, 2, 4, ..., 0, 1, 2],
       [3, 3, 4, ..., 7, 4, 2],
       [5, 2, 4, ..., 4, 1, 2]])

In [343]:
df_x.shape

(8124, 21)

In [344]:
df_y = df.iloc[:, 0].values

In [345]:
df_y

array([1, 0, 0, ..., 0, 1, 0])

In [346]:
df_y.shape

(8124,)

In [347]:
#OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [348]:
onehotencoder_df = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])], remainder='passthrough')

In [349]:
df_x_onehot = onehotencoder_df.fit_transform(df_x).toarray()

In [372]:
df_x_onehot

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [373]:
df_x_onehot.shape

(8124, 112)

In [306]:
#Divisão das bases em treinamento e teste

In [378]:
df_x_onehot_train, df_x_onehot_test, df_y_train, df_y_test = train_test_split(df_x_onehot, df_y, test_size = 0.15, random_state = 0)

In [379]:
df_x_onehot_train.shape, df_y_train.shape

((6905, 112), (6905,))

In [380]:
df_x_onehot_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [381]:
df_y_train

array([0, 1, 0, ..., 0, 0, 0])

In [382]:
df_x_onehot_test.shape, df_y_test.shape

((1219, 112), (1219,))

In [385]:
df_x_onehot_test

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [386]:
df_y_test


array([1, 0, 0, ..., 0, 0, 1])

In [387]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

In [396]:
random_forest_df = RandomForestClassifier(n_estimators=1, criterion='entropy', random_state = 0)
random_forest_df.fit(df_x_onehot_train, df_y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1, random_state=0)

In [397]:
previsoes_randomforest = random_forest_df.predict(df_x_onehot_test)

In [398]:
previsoes_randomforest

array([1, 0, 0, ..., 0, 0, 1])

In [399]:
df_y_test

array([1, 0, 0, ..., 0, 0, 1])

In [400]:
from sklearn.metrics import accuracy_score, classification_report
accuracy_score(df_y_test, previsoes_randomforest)

1.0

In [401]:
#knn - baseado em instâncias
from sklearn.neighbors import KNeighborsClassifier
knn_df = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p = 2)
knn_df.fit(df_x_onehot_train, df_y_train)

KNeighborsClassifier()

In [402]:
previsoes_knn = knn_df.predict(df_x_onehot_test)

In [403]:
previsoes_knn

array([1, 0, 0, ..., 0, 0, 1])

In [404]:
accuracy_score(df_y_test, previsoes_knn)

1.0

In [406]:
#Naiva Bayes
from sklearn.naive_bayes import GaussianNB
naive_df = GaussianNB()
naive_df.fit(df_x_onehot_train, df_y_train)

GaussianNB()

In [408]:
previsoes_nb = naive_df.predict(df_x_onehot_test)

In [409]:
accuracy_score(df_y_test, previsoes_nb)

0.9876948318293683